on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 克隆当前仓库
        uses: actions/checkout@v4

      - name: 安装 Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 打包项目为 Windows 可执行文件
      - name: 打包项目
        run: |
          pip install pyinstaller
          pyinstaller --onefile --name code-merger-py --icon icon.ico --hidden-import tiktoken.registry main.py

      # 上传到 Artifacts
      - name: 上传 Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: code-merger-py
          path: dist/code-merger-py.exe
