name: build

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 克隆当前仓库
        uses: actions/checkout@v4

      - name: 安装 Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: 安装依赖
        run: pip install -r requirements.txt


      # Build python script into a stand-alone exe
      - name: 打包
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true
          output-dir: dist
          output-file: code-merger-py.exe
          windows-icon-from-ico: icon.ico

      # 上传到 Artifacts
      - name: 上传 Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: code-merger-py
          path: dist/code-merger-py.exe
