name: build

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 克隆当前仓库
        uses: actions/checkout@v4

      - name: 安装 Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 打包
        run: |
          pip install nuitka
          nuitka --standalone --windows-icon-from-ico=icon.ico --output-dir=dist --output-filename=code-merger-py.exe main.py

      # 上传到 Artifacts
      - name: 上传 Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: code-merger-py
          path: dist/code-merger-py.exe
